name: Deploy to cloud.ru

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  REGISTRY: omnimap.cr.cloud.ru

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: omnimap-back
            context: services/omnimap-back
          - name: omnimap-front
            context: services/omnimap-front
          - name: omnimap-sync
            context: services/omnimap-sync
          - name: llm-gateway
            context: services/llm-gateway
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CLOUD_RU_USERNAME }}
          password: ${{ secrets.CLOUD_RU_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service.context }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.service.name }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ matrix.service.name }}:latest
          platforms: linux/amd64

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            ENV="prod"
          else
            ENV="dev"
          fi
          kubectl apply -k deploy/kubernetes/overlays/${ENV}
          kubectl rollout status deployment/omnimap-back -n omnimap --timeout=300s
          kubectl rollout status deployment/omnimap-front -n omnimap --timeout=300s
          kubectl rollout status deployment/omnimap-sync -n omnimap --timeout=300s
          kubectl rollout status deployment/llm-gateway -n omnimap --timeout=300s
